### ISSUE TITLE
Cannot close menus on iOS

### ISSUE THREAD

**Issue by p-gentili** [jacksalici/salinger-theme#1] opened 2023-08-12 20:09 UTC
Using any iOS browser, it's not possible to close the menu without tapping on one entry. It happens for both menus: header and footer.

### How to reproduce 
1. Visit the demo website
2. Tap on the hamburger menu
3. Tap outside of the menu view list to close it

_Expected result_: the menu view disappears
_Actual result_: the menu view is still there

**Comment by jacksalici** [comment] 2023-08-14 10:16
Hello, thank you for have reached me. I will investigate further the problem. Actually, the menus are handled by DaisyUI, so the odds are that the problem is there.

**Comment by p-gentili** [comment] 2023-08-14 10:36
> Hello, thank you for have reached me. I will investigate further the problem. Actually, the menus are handled by DaisyUI, so the odds are that the problem is there.

Mh right, I can see there are a couple of related issues on their repo:
1. https://github.com/saadeghi/daisyui/issues/234
2. https://github.com/saadeghi/daisyui/issues/1737

The workaround seems to be on the user side though. Thanks!

EDIT: if you don't have a device to test it just reach me out.

**Comment by jacksalici** [comment] 2023-08-14 11:08
Thanks for the reference, I keep this issue open until will understand better the problem. 
I'm going to update you in a couple of days.

**Comment by jacksalici** [comment] 2023-08-15 17:41
Hello, with the last commits, I should have solved the bug. I tried it on my iPad and it worked fine, if you want to check on your device too, then I will create a new release and close the issue. Thank you.

**Comment by p-gentili** [comment] 2023-08-15 17:57
It works beautifully, TYVM.

**Closed as completed** 2023-08-15 18:42 UTC
Labels: bug
